on:
  push:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest  # Ensure the correct runner
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests azure-identity azure-mgmt-purview azure-mgmt-resource azure-purview-catalog

      - name: Set Dynamic Variables
        run: |
          echo "AZURE_TENANT_ID=${{ vars.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_ID=${{ vars.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Read Parameter File and Onboard New Data Sources
        id: read_csv_python
        run: |
          python - <<EOF
          import csv, os, json
          from base64 import b64encode

          file_path = "./cosmos_collection_manager.csv"
          if not os.path.exists(file_path):
              raise FileNotFoundError(f"File not found: {file_path}")

          with open(file_path, "r") as file:
              reader = csv.DictReader(file)
              data_rows = list(reader)

          # Simulating filtering of new data sources
          filtered_data = [row for row in data_rows if row["DatabaseName"] not in ["ExistingDB1", "ExistingDB2"]]

          # Convert JSON to Base64 to safely pass between jobs
          json_data = json.dumps(filtered_data)
          b64_json = b64encode(json_data.encode()).decode()

          with open("task_data.json", "w") as f:
              f.write(b64_json)

          print(b64_json)  # Print for debugging
          EOF

          echo "filtered_data=$(cat task_data.json)" >> $GITHUB_ENV

    outputs:
      filtered_data: ${{ env.filtered_data }}

  processed-data:
    needs: run-script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Process Filtered Data
        run: |
          echo "Processing task data..."
          task_data="${{ needs.run-script.outputs.filtered_data }}"

          if [[ -z "$task_data" ]]; then
            echo "Error: No data received!"
            exit 1
          fi

          echo "$task_data" | python - <<EOF
          import sys, json
          from base64 import b64decode

          encoded_data = sys.stdin.read().strip()
          if not encoded_data:
              print("Error: Received empty data")
              sys.exit(1)

          try:
              decoded_json = json.loads(b64decode(encoded_data).decode())
          except Exception as e:
              print(f"JSON decoding error: {e}")
              sys.exit(1)

          for item in decoded_json:
              print("Deploying data source:")
              for key, value in item.items():
                  print(f"- {key}: {value}")
          EOF
